parameters:
  smartesb.consumers.queue.class: Smartbox\Integration\FrameworkBundle\Components\Queues\QueueConsumer

services:
  smartesb.consumers.queue:
      class: %smartesb.consumers.queue.class%
      calls:
          - [ setSmartesbHelper, [@smartesb.helper]]