queues.stomp:
  pattern: "stomp://{host}/{queue}"
  defaults:
    _connector: @smartesb.connectors.queue
    queue_driver: @smartesb.default_queue_driver
    prefix: null
  requirements:
    queue: "[a-zA-Z0-9/]+"

queues.generic:
  pattern: "queue://{host}/{queue}"
  defaults:
    _connector: @smartesb.connectors.queue
    queue_driver: @smartesb.default_queue_driver
    prefix: null
  requirements:
    queue: "[a-zA-Z0-9/]+"

db.mongo:
  pattern: "mongo://{database}/{collection}"
  defaults:
    _connector:
    db_driver: @smartesb.connectors.mongodb
    prefix: null
    database: smartesb
  requirements:
    database: "[_\-a-zA-Z0-9/]+"
    collection: "[_\-a-zA-Z0-9/]+"

direct:
  pattern: "direct://{host}/{subroutine}"
  defaults:
    _connector: @smartesb.connector.direct