queues.stomp:
  pattern: "stomp://{host}/{queue}"
  defaults:
    _connector: @smartesb.connectors.queue
    queue_driver: @smartesb.default_queue_driver
    prefix: null
  requirements:
    queue: "[a-zA-Z0-9/]+"

queues.generic:
  pattern: "queue://{queue_driver}/{queue}"
  defaults:
    _connector: @smartesb.connectors.queue
    prefix: null
  requirements:
    queue: "[a-zA-Z0-9/]+"

nosql.generic:
  pattern: "nosql://{nosql_driver}/{collection}"
  defaults:
    _connector: @smartesb.connectors.nosql
    prefix: db_
  requirements:
    collection: "[_\-a-zA-Z0-9/]+"

direct:
  pattern: "direct://{host}/{subroutine}"
  defaults:
    _connector: @smartesb.connector.direct