queues.generic:
  pattern: "queue://{queue_driver}/{queue}"
  defaults:
    _class: Smartbox\Integration\FrameworkBundle\Endpoints\QueueEndpoint
    _producer: @smartesb.producers.queue
    _consumer: @smartesb.consumers.queue
    prefix: "%kernel.environment%/fv_%flows.version%/"
  requirements:
    queue: "[a-zA-Z0-9/]+"

nosql.generic:
  pattern: "nosql://{nosql_driver}/{collection}"
  defaults:
    _class: Smartbox\Integration\FrameworkBundle\Endpoints\NoSQLEndpoint
    _producer: @smartesb.producers.nosql
    prefix: db_
  requirements:
    collection: "[_\-a-zA-Z0-9/]+"

direct:
  pattern: "direct://{path}"
  defaults:
    _producer: @smartesb.producer.direct
  requirements:
    path: "[a-zA-Z0-9/_]+"

events:
  pattern: "queue://{queue_driver}/{queue}"
  defaults:
    _class: Smartbox\Integration\FrameworkBundle\Endpoints\QueueEndpoint
    _producer: @smartesb.producers.queue
    _consumer: @smartesb.consumers.queue
    prefix: "%kernel.environment%/fv_%flows.version%/"
  requirements:
    queue: "[a-zA-Z0-9/]+"
