queues.generic:
  pattern: "queue://{queue_driver}/{queue}"
  defaults:
    _protocol: @smartesb.protocols.queue
    prefix: "%kernel.environment%"
  requirements:
    queue: "[a-zA-Z0-9/]+"
    queue_driver: "[a-zA-Z0-9]+"

direct:
  pattern: "direct://{path}"
  defaults:
    _protocol: @smartesb.protocols.direct
  requirements:
    path: "[a-zA-Z0-9/_]+"

service:
  pattern: "service://{service}/{method}"
  defaults:
    _protocol: @smartesb.protocols.service
  requirements:
    service: "[a-zA-Z0-9/_.-]+"
    method: "[a-zA-Z0-9_]+"