services:
  event_dispatcher:
    class: Smartbox\Integration\FrameworkBundle\Tools\EventsDeferring\EventDispatcher
    arguments:
      $container: '@service_container'

  smartesb.handlers.events:
      class: Smartbox\Integration\FrameworkBundle\Tools\EventsDeferring\DeferredEventsHandler
      calls:
        - [setId, ['smartesb.handlers.events']]
        - [setEventDispatcher, ['@event_dispatcher']]
        - [setFlowsVersion, ["%smartesb.flows_version%"]]

  smartesb.registry.event_filters:
    class: Smartbox\Integration\FrameworkBundle\Tools\EventsDeferring\EventFiltersRegistry
