parameters:
  ########## PRODUCER CLASSES  ##########
  smartesb.producers.direct.class: Smartbox\Integration\FrameworkBundle\Core\Producers\DirectProducer
  smartesb.producers.json_file.class: Smartbox\Integration\FrameworkBundle\Components\JsonFileLoader\JsonFileLoaderProducer
  smartesb.producers.queue.class: Smartbox\Integration\FrameworkBundle\Components\Queues\QueueProducer
  smartesb.producers.nosql.class: Smartbox\Integration\FrameworkBundle\Components\DB\NoSQL\NoSQLProducer

services:
  ########## PRODUCERS  ##########

  smartesb.producer.direct:
      class: %smartesb.producers.direct.class%
      calls:
        - [setItinerariesRouter, [@smartesb.router.itineraries]]

  smartesb.producers.json_file:
      class: %smartesb.producers.json_file.class%
      calls:
        - [setSerializer, [@serializer]]

  # STOMP
  smartesb.producers.queue:
      class: %smartesb.producers.queue.class%
      calls:
        - [setSerializer, [@serializer]]
        - [setDriverRegistry, [@smartesb.drivers.queue._registry]]

  # NoSQL
  smartesb.producers.nosql:
      class: %smartesb.producers.nosql.class%
      calls:
        - [setDriverRegistry, [@smartesb.drivers.nosql._registry]]
