parameters:
  smartesb.registry.endpoints.class: Smartbox\Integration\FrameworkBundle\Helper\EndpointsRegistry
  smartesb.itinerary.class: Smartbox\Integration\FrameworkBundle\Processors\Itinerary

  smartesb.processor.router.class: Smartbox\Integration\FrameworkBundle\Processors\Routing\ContentRouter
  smartesb.processor.multicast.class: Smartbox\Integration\FrameworkBundle\Processors\Routing\Multicast
  smartesb.processor.transformer.class: Smartbox\Integration\FrameworkBundle\Processors\Transformation\Transformer
  smartesb.processor.throw_exception.class: Smartbox\Integration\FrameworkBundle\Processors\ControlFlow\ThrowException

  event_dispatcher.class: Smartbox\Integration\FrameworkBundle\Events\EventDispatcher
#  debug.event_dispatcher.class: Smartbox\Integration\FrameworkBundle\Events\EventDispatcher

  smartif.util.evaluator.class: Smartbox\Integration\FrameworkBundle\Util\ExpressionEvaluator
  smartif.serialization.handler.itinerary.class: Smartbox\Integration\FrameworkBundle\Serialization\ItineraryHandler
  smartesb.internal_router.class: Smartbox\Integration\FrameworkBundle\Routing\InternalRouter
  smartesb.map.itineraries.class: Smartbox\Integration\FrameworkBundle\Routing\ItinerariesMap
  smartesb.event_listener.fatal_error.class: Smartbox\Integration\FrameworkBundle\EventListener\FatalErrorListener
  smartbox.monolog.formatter.json.class: Smartbox\Integration\FrameworkBundle\Util\JMSSerializerFormatter

  smartif.serialization.handler.mongodate.class: Smartbox\Integration\FrameworkBundle\Storage\Driver\MongoDBDateHandler

  smartif.router.itineraries.options:
      cache_dir: %kernel.cache_dir%
      debug: %kernel.debug%
      generator_class: 'SmartesbItinerariesUrlGenerator'
      generator_base_class: %router.options.generator_base_class%
      generator_dumper_class: %router.options.generator_dumper_class%
      generator_cache_class: %router.options.generator.cache_class%
      matcher_class: %router.options.matcher_class%
      matcher_base_class: %router.options.matcher_base_class%
      matcher_dumper_class: %router.options.matcher_dumper_class%
      matcher_cache_class: 'SmartesbItinerariesUrlMatcher'

  smartif.router.connectors.options:
      cache_dir: %kernel.cache_dir%
      debug: %kernel.debug%
      generator_class: 'SmartesbConnectorsUrlGenerator'
      generator_base_class: %router.options.generator_base_class%
      generator_dumper_class: %router.options.generator_dumper_class%
      generator_cache_class: %router.options.generator.cache_class%
      matcher_class: %router.options.matcher_class%
      matcher_base_class: %router.options.matcher_base_class%
      matcher_dumper_class: %router.options.matcher_dumper_class%
      matcher_cache_class: 'SmartesbConnectorsUrlMatcher'

services:
  smartif.util.evaluator:
      class: %smartif.util.evaluator.class%

  smartif.serialization.handler.itinerary:
      class:  %smartif.serialization.handler.itinerary.class%
      calls:
        - [setContainer, [@service_container]]
      tags:
        - { name: jms_serializer.subscribing_handler }

  smartif.serialization.handler.mongodate:
      class: %smartif.serialization.handler.mongodate.class%
      tags:
        - { name: jms_serializer.subscribing_handler }

  smartif.router.itineraries:
      class: %smartesb.internal_router.class%
      arguments:
        - @service_container
        - "%kernel.root_dir%/config/routing_itineraries.yml"
        - %smartif.router.itineraries.options%
      tags:
        - { name: monolog.logger, channel: "router.itineraries" }

  smartif.router.connectors:
      class: %smartesb.internal_router.class%
      arguments:
        - @service_container
        - "%kernel.root_dir%/config/routing_connectors.yml"
        - %smartif.router.connectors.options%
      tags:
        - { name: monolog.logger, channel: "router.connectors" }

  smartif.router.itineraries.cache_warmer:
    class: %router.cache_warmer.class%
    arguments:
      - @smartif.router.itineraries
    tags:
      - { name: "kernel.cache_warmer" }

  smartif.router.connectors.cache_warmer:
    class: %router.cache_warmer.class%
    arguments:
      - @smartif.router.connectors
    tags:
      - { name: "kernel.cache_warmer" }

  smartesb.map.itineraries:
    class: %smartesb.map.itineraries.class%

  smartesb.routing.itineraries_routes_loader:
      class: Smartbox\Integration\FrameworkBundle\Routing\ItinerariesRoutesLoader
      calls:
          - [ setContainer, [ @service_container ] ]
      tags:
          - { name: routing.loader }

  smartif.registry.event_filters:
    class: Smartbox\Integration\FrameworkBundle\Events\EventFiltersRegistry

  smartbox.monolog.formatter.json:
      class: %smartbox.monolog.formatter.json.class%
      calls:
          - [setSerializer, [@serializer]]

  smartesb.registry.endpoints:
      class: %smartesb.registry.endpoints.class%

  smartesb.event_listener.fatal_error:
      class: %smartesb.event_listener.fatal_error.class%
      tags:
        - { name: kernel.event_listener, event: smartesb.event.error, method: onErrorEvent }
