addons:
  hosts:
    - rabbit.local
    - database.local

language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=2.8.*

before_install:
  - phpenv config-add travis/z_php.ini
#  - bash travis/install-apcu-pecl.sh

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
#  - composer self-update
  - composer install --no-interaction

script:
  - bin/simple-phpunit --coverage-text

notifications:
  email:
    recipients:
      - si-integration@smartandco.com
    on_success: change 
    on_failure: always

services:
  - rabbitmq
  - mongodb