addons:
  hosts:
    - rabbit
    - database.local
  apt_packages:
    - librabbitmq-dev
    - rabbitmq-server
language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

matrix:
  allow_failures:
    - php: '7.3'

env:
  - SYMFONY_VERSION=2.8.* SYMFONY_PHPUNIT_VERSION=6.5
  - SYMFONY_VERSION=3.4.* SYMFONY_PHPUNIT_VERSION=6.5

before_install:
  - |
    # General configuration
    set -e
    stty cols 120
    nanoseconds () {
        local cmd="date"
        local format="+%s%N"
        local os=$(uname)
        if hash gdate > /dev/null 2>&1; then
          cmd="gdate"
        elif [[ "$os" = Darwin ]]; then
          format="+%s000000000"
        fi
        $cmd -u $format
    }
    export -f nanoseconds
  - phpenv config-add travis/z_php.ini

before_script:
  - echo $TRAVIS_PHP_VERSION
  - sudo systemctl enable rabbitmq-server
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo systemctl restart rabbitmq-server
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --no-interaction

script:
  - SYMFONY_PHPUNIT_VERSION=6.5 SYMFONY_DEPRECATIONS_HELPER=462 bin/simple-phpunit --coverage-text # TODO: Fix deprecations

notifications:
  email:
    recipients:
      - si-integration@smartandco.com
    on_success: change 
    on_failure: always

services:
  - rabbitmq
  - mongodb
